#pragma newdecls required
#pragma semicolon 1

#include <necro_multipath/gamemodes/gungame/core>
#include <necro_multipath/gamemodes/gungame/events>
#include <necro_multipath/gamemodes/gungame/items>
#include <necro_multipath/gamemodes/gungame/round>
#include <necro_multipath/gamemodes/gungame/utils>
#include <necro_multipath/gamemodes/gungame/map>
#include <necro_multipath/gamemodes/gungame/votes>